chore: update dotfiles/vimrc

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -18,21 +18,21 @@ if [ -d ~/.git ]; then
 fi
 
 # any current, conflicting dotfiles will be moved here
-DOTFILES_BACKUP_DIR="$HOME/.dotfiles-backup"
+backup_dir="${DOTFILES:-$HOME/.dotfiles}-backup"
+cache_dir="${DOTFILES:-$HOME/.dotfiles}/cache"
+mkdir -p "$backup_dir" "$cache_dir"
 
 # Don't use SSH to clone if there is no SSH key on the machine
 # This is for when I spin up a new VM and don't want to login to GitHub
 if find ~/.ssh -type f -name '*.pub' | wc -l | xargs test 0 -eq; then
-    GIT_URL=https://github.com/benelan/dotfiles
+    repo_url="https://github.com/benelan/dotfiles"
 else
-    GIT_URL=git@github.com:benelan/dotfiles
+    repo_url="git@github.com:benelan/dotfiles"
 fi
 
-git clone --bare "$GIT_URL" "$HOME/.git"
+git clone --bare "$repo_url" "$HOME/.git"
 
-dot() {
-    /usr/bin/git --git-dir="$HOME"/.git/ --work-tree="$HOME" "$@"
-}
+dot() { /usr/bin/git --git-dir="$HOME"/.git/ --work-tree="$HOME" "$@"; }
 
 # Make sure fetching works correctly for all branches
 dot config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
@@ -47,7 +47,7 @@ dot branch --set-upstream-to=origin/master master
 if dot checkout >/dev/null 2>&1; then
     printf "\nChecked out dotfiles\n" >&2
 else
-    printf "\n> Backing up conflicting dotfiles to %s\n" "$DOTFILES_BACKUP_DIR" >&2
+    printf "\n> Backing up conflicting dotfiles to %s\n" "$backup_dir" >&2
     # Get the list of files that need to be backed up
     files=$(dot checkout 2>&1 | grep -e "^\s")
     printf "%s\n" "$files" >&2
@@ -62,54 +62,32 @@ else
     # Using dirname is easier but won't work on OSX
     # dirs=$(echo "$files" | xargs dirname)
 
-    # Create the directories in $DOTFILES_BACKUP_DIR
-    mkdir -p "$DOTFILES_BACKUP_DIR"
-    echo "$dirs" | xargs -I{} mkdir -p "$DOTFILES_BACKUP_DIR/{}"
+    # Create the directories in $backup_dir
+    echo "$dirs" | xargs -I{} mkdir -p "$backup_dir/{}"
 
     # Move the conflicting files to the new directories
-    echo "$files" | xargs -I{} mv {} "$DOTFILES_BACKUP_DIR/{}"
+    echo "$files" | xargs -I{} mv {} "$backup_dir/{}"
 
     # Checkout the dotfiles now that there are no conflicts.
-    # Move the files from $DOTFILES_BACKUP_DIR to $HOME to undo the script
+    # Move the files from the backup dir to $HOME to undo the script:
     # $ mv ~/.dotfiles-backup/* ~/
     if ! dot checkout; then
-        printf "\nError: unable to initialize the dotfiles\n" >&2
+        printf "\nError: unable to setup the dotfiles\n" >&2
         exit 1
     else
         printf "\nChecked out dotfiles\n" >&2
     fi
 fi
+unset files dirs repo_url backup_dir cache_dir
 
-unset files
-unset GIT_URL
-unset DOTFILES_BACKUP_DIR
-
-# Make the bins and scripts executable
-printf "\n> Making scripts and bins executable\n" >&2
+# Make the bins executable
+printf "\n> Making scripts executable\n" >&2
 [ -d ~/.dotfiles/bin/ ] && chmod +x ~/.dotfiles/bin/*
-[ -d ~/.dotfiles/scripts/ ] && chmod +x ~/.dotfiles/scripts/*
 
-if [ -d /usr/share/bash-completion/completions ]; then
-    printf "\n>  Copying completion scripts to system\n\n" >&2
-
-    sudo cp ~/.dotfiles/shell/completions/0_tmux.completion.sh \
-        /usr/share/bash-completion/completions/tmux
-
-    sudo cp ~/.dotfiles/shell/completions/0_fasd.completion.sh \
-        /usr/share/bash-completion/completions/fasd
-
-    sudo cp ~/.dotfiles/shell/completions/0_npm.completion.sh \
-        /usr/share/bash-completion/completions/npm
-fi
-
-# Must install libs before they can be pwn'd
 printf "\n> Installing git submodules\n\n" >&2
-cd && dot submodule update --init --recursive
-
-# fzf install script
-[ ! "$(command -v fzf)" ] &&
-    ~/dev/lib/fzf/install \
-        --bin --key-bindings --completion --no-update-rc
-
-printf "\n+ Initialization complete!\n" >&2
+cd
+dot submodule update --init --recursive
 cd -
+
+bash -l
+printf "\n+ Setup complete!\n" >&2
